name: Deny Self approvals
description: Deny Self approvals
author: Shunsuke Suzuki
branding:
  icon: shield
  color: purple
inputs:
  github_token:
    description: |
      GitHub Access Token
      pull_requests:write - Dismiss approvals
      contents:read - List commits in pull requests
    required: false
  ignore_unknown_commit:
    description: |
      Ignore unknown commits.
    required: false
    default: "false"
runs:
  using: composite
  steps:
    # Install deny-self-approve by aqua
    - run: echo "value=$GITHUB_ACTION_PATH/aqua/aqua.yaml" >> "$GITHUB_OUTPUT"
      id: aqua_config
      shell: bash
    - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      with:
        aqua_version: v2.44.1
        skip_install_aqua: "true"
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}

    - shell: bash
      run: deny-self-approve -v
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}

    - run: |
        opts=""
        if [ "$IGNORE" = "true" ]; then
          opts="--ignore-unknown-commit"
        fi
        if ! deny-self-approve $opts validate --dismiss; then
          echo "::error:: Approval is required from anyone who did not push commits to the pull request https://github.com/suzuki-shunsuke/deny-self-approve-action" >&2
          exit 1
        fi
      shell: bash
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        GITHUB_TOKEN: ${{github.token}}
        IGNORE: ${{inputs.ignore_unknown_commit}}
