name: Deny Self approvals
description: Deny Self approvals
author: Shunsuke Suzuki
branding:
  icon: shield
  color: purple
inputs:
  github_token:
    description: |
      GitHub Access Token
      pull_requests:write - Dismiss approvals
      contents:read - List commits in pull requests
    required: false
outputs:
  has_not_linked_commit:
    description: Whether there are commits not linked to a GitHub User
    value: ${{ steps.deny.outputs.has_not_linked_commit }}
runs:
  using: composite
  steps:
    # Install deny-self-approve by aqua
    - run: echo "value=$GITHUB_ACTION_PATH/aqua/aqua.yaml" >> "$GITHUB_OUTPUT"
      id: aqua_config
      shell: bash
    - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.48.2
        skip_install_aqua: "true"
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}

    - shell: bash
      run: deny-self-approve -v
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}

    - run: |
        tempfile=$(mktemp)
        echo "has_not_linked_commit=false" >> "$GITHUB_OUTPUT"
        if ! deny-self-approve validate 2> >(tee -a "$tempfile" >&2); then
          if grep -q "commit isn't linked to a GitHub User" "$tempfile"; then
            echo "::error:: Commit isn't linked to a GitHub User. https://github.com/suzuki-shunsuke/deny-self-approve/blob/main/docs/001.md" >&2
            echo "has_not_linked_commit=true" >> "$GITHUB_OUTPUT"
            exit 1
          fi
          echo "::error:: Approval is required from anyone who did not push commits to the pull request https://github.com/suzuki-shunsuke/deny-self-approve-action" >&2
          exit 1
        fi
      shell: bash
      id: deny
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        GITHUB_TOKEN: ${{github.token}}
